# docker-compose.yml
version: "3.7"

services:
  trino-coordinator:
    image: trinodb/trino:405
    container_name: trino-coordinator
    volumes:
    - source: ./target/trino-db2-405
      target: /usr/lib/trino/plugin/db2
      type: bind
    - source: ./conf/trino/catalog
      target: /etc/trino/catalog
      type: bind
    ports:
      - "8080:8080"

  db2:
    image: alleeex/serp-db2:latest
    container_name: "db2"
    privileged: true
    ports:
      - "50000:50000"
      - "55000:55000"
    environment:
      DBNAME: "${DBNAME}"
      DB2INST1_PASSWORD: "${DB2INST1_PASSWORD}"
      LICENSE: "${LICENSE}"
      DB2INSTANCE: "${DB2INSTANCE}"
    volumes:
      - db2inst1:/database
    restart: unless-stopped

volumes:
  db2inst1: